#!/usr/bin/env bash
# this script copies a file to the server

if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Disable strict host key checking for scp
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Use scp to transfer the file to the user's home directory on the server
scp $SCP_OPTIONS -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~/"
