#!/usr/bin/env bash
# Update the package list and install Nginx with automatic "yes" answers to prompts
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF'
sudo /etc/init.d/nginx restart
