#!/usr/bin/env bash
# Check if the script is run as root

if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root or with sudo."
  exit 1
fi

# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy=2.0.\*
# Create a custom HAProxy configuration
echo "global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend load-balancer
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server 295619-web-01 54.164.64.95:80 check
    server 295619-web-02 52.91.118.112:80 check" > /etc/haproxy/haproxy.cfg
# Enable HAProxy service
systemctl enable haproxy

# Restart HAProxy service
sudo service haproxy restart
# Verify HAProxy status
sudo service haproxy stat
